#SPDX-License-Identifier: GPL-2.0-only

ifeq ($(ENABLE_VENDOR_CUTTLEFISH), true)
# Build virtio-video kernel driver

BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/virtio_video.ko
# BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/virtio_video.ko
# BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/virtio_video.ko
endif # ENABLE_VENDOR_CUTTLEFISH
